(function () {
  'use strict'

  const supporters = [
    "( ﾟ Д ﾟ )",
    "＼ﾅｶﾞﾓﾝ／",
    "☆☆☆☆☆bancho☆☆☆☆☆",
    "★★かっちゃん★★",
    "１０式",
    "3106/長夢",
    "45yukura78",
    "aa",
    "agu",
    "akai170yen",
    "akasata",
    "akiaki",
    "ant",
    "aresta",
    "asuna",
    "ATTI",
    "Azure",
    "b-dolo",
    "Bob",
    "bono",
    "BUNNY",
    "Casper-01",
    "Closer",
    "cluster",
    "Coffee屋",
    "cook",
    "cyarlie",
    "Darjeeling",
    "defcon5",
    "DiSK",
    "Django",
    "donbuly",
    "dontbecruel",
    "eagle1",
    "Edgar",
    "eiji",
    "Ek",
    "exe",
    "Ｆ・Ｍ・バーチ",
    "Ｆ蛙",
    "Gao",
    "gasinsow",
    "gg",
    "gimp",
    "gouma",
    "guest",
    "gunboy",
    "Gアンドレ",
    "haas",
    "hakuneru",
    "HAL",
    "hamibon",
    "hazel",
    "hetter@cc110",
    "hideki",
    "HIDE-T",
    "HiroHiro",
    "HK_SOS",
    "hogehoge",
    "ikeyan",
    "IMA＠ながもん提督",
    "inishie",
    "Ino",
    "invidia",
    "ISE-H",
    "jackhit",
    "JIN",
    "JINDAI",
    "k3vat",
    "kagero",
    "KATSU",
    "Kein",
    "kent_110",
    "KENTわん",
    "kiaki",
    "kirie",
    "kon",
    "konkon6696",
    "korosuke",
    "kuro",
    "kyo",
    "M Susumu",
    "m7@...",
    "MAISA",
    "mako",
    "manyuki",
    "Martin",
    "masa",
    "mazin",
    "meerkat7",
    "miffysan",
    "millupp",
    "moki-sa",
    "montecore",
    "mutts15",
    "Nag.",
    "nano",
    "nanohana",
    "Nb+1",
    "nemus",
    "Nimoo",
    "no88",
    "Noir",
    "noki",
    "nonbiri194",
    "nor",
    "nyaka",
    "o＜－∀－＞o ",
    "P.I.P",
    "paru",
    "piero",
    "Pirozhki",
    "Pluto",
    "ReZEL",
    "Riley Hale",
    "rim",
    "Robo03",
    "rock1374",
    "Rocma",
    "rouge",
    "RTMS-BOSS",
    "sage",
    "ｓａｒａ",
    "sara",
    "SJ",
    "sonnen",
    "sora",
    "ＳＳＲ",
    "STREAM",
    "submariner",
    "sumikko",
    "TA5",
    "tago35911",
    "taka-107",
    "take1",
    "take-night",
    "Taro G",
    "tarolee",
    "TATSU",
    "Teena",
    "Tenere",
    "T-lex",
    "todogon",
    "toraness",
    "totokaka",
    "toufu",
    "touhu",
    "ukyu",
    "unique",
    "unko",
    "uwaaan",
    "vatel",
    "Watson",
    "whity",
    "winglayer",
    "xf108",
    "xxx",
    "yaiba",
    "y-puppy",
    "yuricube",
    "yuuji",
    "yuyuyu",
    "zag",
    "zaQ",
    "アヴ",
    "あかねちゃん",
    "アシダカ",
    "あしるん",
    "あすかっち",
    "あつき",
    "アナログマ",
    "アミノ酸飲料",
    "あるが",
    "いーくん",
    "いっさ",
    "インコ",
    "ｲ反装",
    "うなぎ",
    "エイト",
    "エシード",
    "エチエンヌ",
    "エボシ",
    "おこめ",
    "おさしみ",
    "おにやん",
    "オリおじ",
    "お船",
    "お湯",
    "かちあき",
    "かぴたん",
    "かふぇ俺",
    "かものはし",
    "がらむ",
    "カリス",
    "か考え",
    "キアラ",
    "キサラギ",
    "きさりあ",
    "きゃりー",
    "くう",
    "ぐっさん",
    "くる～ん",
    "ゲスト",
    "こいし",
    "ゴールデン",
    "ゴゴ",
    "コニシキ",
    "コパール",
    "こまいぬ",
    "コンブとワカメ",
    "さーいえすさー",
    "サイキョー",
    "さりな",
    "さるモドキ",
    "じゃいろ@283プロ",
    "シャンブラー",
    "しょううん",
    "しょう提督",
    "スイ",
    "スーパーどらい",
    "すくも丁",
    "スター★ファイター",
    "スミヒト",
    "せつよ",
    "セラール",
    "セリム",
    "そら",
    "たかゆき",
    "たけ",
    "タケちゃん",
    "だの！！",
    "たま",
    "ダム",
    "タンクレーディ· G",
    "だんだん星仁P",
    "チルノ⑨",
    "ツアル",
    "つぐ",
    "てきとう",
    "てちゅ",
    "トゥール",
    "トシジ",
    "とも",
    "トラック",
    "とり頭",
    "トレノ０４",
    "なお君（旧：殺陣倉）",
    "ながもん",
    "なっちー",
    "ななし",
    "ナマクラ弦馬",
    "ナンツ二曹",
    "ニセＯＩＣ",
    "にゃし",
    "にるせん",
    "ニンニク",
    "ぬいぬい",
    "ヌコミミさん",
    "ぬんぬん",
    "ねこま",
    "ねるお",
    "ののまる",
    "パチェ",
    "パピット",
    "バラモスバンパイア",
    "ばりおす５ｔｈ",
    "はるぺ",
    "はんちょー",
    "バンビ",
    "ﾋｰｸﾞﾗｽ",
    "ひげっち",
    "ビスタ",
    "ヒルト＝Fo・Ar＝オーウェン",
    "ひろくん",
    "ひろゆき",
    "フェンリル",
    "プジョ・夕立",
    "ぷに",
    "フリー素材あそび",
    "ベイクス",
    "ヘビーゲージ",
    "ベン",
    "ポーション",
    "ホーリー",
    "ポコ",
    "マイン",
    "マカロン",
    "マグロお嬢",
    "マスター",
    "ますたー",
    "マダオ",
    "マッチョカーニバル",
    "みーすけ",
    "ミカワマイマイ",
    "みのぶん",
    "もこ草",
    "やくも",
    "ヤッピー",
    "やまなん",
    "やまびこ",
    "ゆーかりきっく",
    "ユウキ",
    "ユースケ",
    "ゆきはね",
    "ゆきや",
    "ユサク",
    "ユダ",
    "ユルティム",
    "ヨッシー",
    "らいらい",
    "ラクセル",
    "ラフィール",
    "リプロワークス",
    "りゅうざき",
    "レインボーおすし",
    "レッドブレイド",
    "れんねる",
    "ロックハート",
    "わぅわぅ",
    "絢辻さんは裏表のない素敵な人です",
    "伊藤信明",
    "一悟一階",
    "一航戦ﾃﾞｰｽ☆ミ",
    "加賀井",
    "霞の嬢",
    "雅弘",
    "海斗",
    "葛城",
    "甘ったれトーマト",
    "艦これアニメ2期",
    "丸目 多聞",
    "吉田JAPAN(YSDJ)",
    "桔龍",
    "響遊結己(おとなが　ゆうき)",
    "金田",
    "銀河",
    "景清",
    "五右衛門",
    "五目飯",
    "伍長P",
    "後藤鈴音",
    "高町はやて",
    "高町レンカ",
    "黒月鉄魔",
    "根岸みにゃも",
    "佐々木",
    "三下",
    "三月のライオン",
    "師走",
    "糸目ネコ",
    "紫電二一型",
    "手書き提督",
    "春永一過",
    "深海提督",
    "人間",
    "瑞₍₍(ง˘ω˘)ว⁾⁾川",
    "瑞鶴ファンクラブ",
    "瑞穂",
    "西野",
    "赤いネコ",
    "赤とんぼ",
    "赤城",
    "赤猫とまと",
    "雪原 白銀",
    "絶望ビリー@黒露",
    "泉ん菩薩",
    "双鶴葉桐",
    "大黒屋",
    "大佐(だいさ)",
    "暖気",
    "中川",
    "帝国技術研究室",
    "底抜け脱線鎮守府",
    "天羽辰",
    "田舎者",
    "島風雪風天津風",
    "灯",
    "藤山高志",
    "肉屋",
    "日下部",
    "日十雨相",
    "猫さん",
    "猫柳GT",
    "破壊大帝",
    "廃墟の隠者（閲覧用アカウント）",
    "八雲ゆきか",
    "番犬チワワ",
    "氷雷",
    "舞鶴鎮守府",
    "風さん",
    "北条",
    "幕之内一歩",
    "抹茶",
    "霧島　翔",
    "冥途大好き",
    "名無し",
    "夜月",
    "野方",
    "誘蛾灯のＴ",
    "夕日ノhoushin",
    "零-Ray-",
    "六月",
    "蕨餅",
    "綺羅大和",
    "苺丸でぃ",
    "荼毘丸",
    "麒麟",
  ]
  

  //-------------------------------------------------------------------------------------------------
  // Webページに支援者一覧を作成する処理
  //-------------------------------------------------------------------------------------------------

  function chCount(str) { // 全角は2文字、半角は1文字として文字数をカウントして返す
    let len = 0;
    for (let i = 0; i < str.length; i++) {
      (str[i].match(/[ -~]/)) ? len += 1 : len += 2;
    }
    return len;
  }

  function getWindowSize() {
    return window.innerWidth;
  }

  function createTable(array, winWidth) { // 名前データをhtml要素の一覧に整形して出力
    let limitNum = 3; // 1行あたりの上限3名
    let limitLetters = winWidth >= 600 ? 81 : 27; // 1行あたりの上限 スマホ27文字 タブレット以上81文字
    let oneLine = document.createElement('div'); // ここに一行分のデータを作成
    oneLine.classList.add('names');
    const nameTable = document.querySelector('main .display .supporters'); // できた行を順次ここに追加

    for (let i = 0; i < array.length; i++) {
      const name = array[i];
      const nameElem = document.createElement('span');
      nameElem.textContent = name;
      const lettersNum = chCount(name);
      limitNum--;
      limitLetters -= lettersNum;

      if (limitNum < 0 || limitLetters < 0) { // 1行の上限を超過する場合は次の行へ
        // 現在の1行分のデータをテーブルに追加してリセット
        nameTable.appendChild(oneLine);
        oneLine = document.createElement('div');
        oneLine.classList.add('names');

        // リミット計算に使っていた変数をリセット
        limitNum = 3;
        limitLetters = winWidth >= 600 ? 81 : 27;

        // 改めてリミットを計算し直す
        limitNum--;
        limitLetters -= lettersNum;
      }

      // 1行分の暫定データに追加
      oneLine.appendChild(nameElem);

      if (array.length - 1 === i) { // 最後のループの時はここで暫定データをテーブルに追加
        nameTable.appendChild(oneLine);
      }
    }
  }
  createTable(supporters, getWindowSize());

  //-------------------------------------------------------------------------------------------------
  // ウィンドウサイズ変更でレイアウト調整する処理
  //-------------------------------------------------------------------------------------------------

  function winResize(){
    let timeoutID = 0;
    let delay = 500;

    window.addEventListener("resize", () => {
      clearTimeout(timeoutID);
      timeoutID = setTimeout(function(){
        location.reload();
      }, delay);
    }, false);
  };
  winResize();
})();